### ISSUE TITLE
Clicking Try again or back button takes me to the main screen but I have to fill in my details

### ISSUE THREAD

**Issue by jpa458** [sytac/play#20]
Preserve user details and a clear data button on the form ideally visible in this situation.

**Comment by Industrial** [comment]
Should be fixed.

**Comment by jpa458** [comment]
Partially Fixed - when I land on the page with my data filled in I can no longer select a quiz even though data is entered

**Comment by Industrial** [comment]
Should be fixed now. I decided to never disable the buttons to fix this. You can click them but they will validate the form first.

**Comment by jpa458** [comment]
Not fixed - after clicking try again I land on the main screen with my details filled in but I cannot start a quiz. buttons are disabled.

**Comment by Industrial** [comment]
This should now be deployed.

**Comment by jpa458** [comment]
Fixed
