### ISSUE TITLE
No spacing between letter and box

### ISSUE THREAD

**Issue by edbaedba** [sytac/play#7]
When selecting any kind of box-entry, I see that the text is connected to the box without a space. I expect that there is a "space" between these two things.

**Comment by Industrial** [comment]
Should be fixed

**Comment by jpa458** [comment]
Partially fixed : the last check box for sytac terms and consditions is not covered by this fix

**Comment by Industrial** [comment]
Fixed

**Comment by jpa458** [comment]
Fixed, closing
